### ISSUE TITLE
Error ELIFECYCLE

### ISSUE THREAD

**Issue by RyenNelsen** [atom/git-utils#39]
When attempting to install [`git-projects`](https://github.com/prrrnd/atom-git-projects) I get the following error:

```
Installing “git-projects@1.11.1” failed.

> git-utils@3.0.0 install C:\Users\rnelsen\AppData\Local\Temp\apm-install-dir-115224-10224-1bnh5am\node_modules\git-projects\node_modules\git-utils
> node-gyp rebuild


C:\Users\rnelsen\AppData\Local\Temp\apm-install-dir-115224-10224-1bnh5am\node_modules\git-projects\node_modules\git-utils>node "C:\Users\rnelsen\AppData\Local\atom\app-0.187.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\rnelsen\\AppData\\Local\\atom\\app-0.187.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\rnelsen\\AppData\\Local\\atom\\app-0.187.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\rnelsen\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\rnelsen\\.atom\\.apmrc" "install" "C:\\Users\\rnelsen\\AppData\\Local\\Temp\\d-115224-10224-dz6ybe\\package.tgz" "--target=0.21.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! git-utils@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-utils@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.
```

**Comment by iyogeshjoshi** [comment]
I'm also facing the same problem while updating <code>[git-projects](https://github.com/prrrnd/atom-git-projects)</code> on my ubuntu machine following is the complete log for same 
```shell
Updating to “git-projects@1.11.1” failed.Hide output…
 
> git-utils@3.0.0 install /tmp/apm-install-dir-115225-7298-1rjpl3u/node_modules/git-projects/node_modules/git-utils
> node-gyp rebuild
 
 
Usage: gyp_main.py [options ...] [build_file ...]
 
gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-33-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-115225-7298-1rjpl3u/node_modules/git-projects/node_modules/git-utils
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 3.16.0-33-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/iyogeshjoshi/.atom/.apm/.apmrc" "--userconfig" "/home/iyogeshjoshi/.atom/.apmrc" "install" "/tmp/d-115225-7298-1x2y55n/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
 
npm ERR! git-utils@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-utils@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115225-7298-1rjpl3u/npm-debug.log
```

**Comment by kevinsawicki** [comment]
> gyp_main.py: error: no such option: --no-parallel

@iyogeshjoshi This error can be solved by following the steps here: https://github.com/TooTallNate/node-gyp/issues/426

**Comment by kevinsawicki** [comment]
> RyenNelsen

Can you run `apm -v` and include the output here?

**Comment by RyenNelsen** [comment]
Sure:

```
> apm -v
apm  0.149.0
npm  2.5.1
node 0.10.35
python 3.4.2
git 1.9.4.msysgit.0
visual studio
```

Currently using Atom version 0.188.

**Comment by iyogeshjoshi** [comment]
@kevinsawicki yeah that worked for me :+1:  thanks :)

**Comment by kevinsawicki** [comment]
@RyenNelsen Do you have visual studio installed? It is required to compile this module.

Based on your `apm -v` output it looks like it is either not installed, or not being detected correctly.

**Comment by RyenNelsen** [comment]
@kevinsawicki Then you may want to have a talk with prrrnd/atom-git-projects#19 because prrrnd would be forcing everyone to install VS to just use their plugin, and they feel that it's your package causing the error. Shouldn't a pre-compiled version be included in prrrnd's package?

I did install VS 2013 SP4, and it still didn't compile though, just FYI.

**Comment by kevinsawicki** [comment]
>  and they feel that it's your package causing the error

This library is just a regular node module, node modules can contain native code that requires a compiler be available for building.  That error is expected if you either don't have those tools installed or they aren't being detected correctly by node-gyp.

> Shouldn't a pre-compiled version be included in prrrnd's package?

That is up to the package.

I'm going to close out this issue since this error isn't something that can be fixed by this library, it will be the same error you will see whenever node-gyp tries to compile native code and can't find the tools required.
